@startuml
hide circle
'skinparam monochrome true
skinparam classAttributeIconSize 0
skinparam backgroundcolor white
'skinparam groupInheritance 2


class Fruit {
    + nom : String
    + prix : Double
    + quantite : Int
}

class FruitDAO <<interface >> {
donneLesFruits() : List<Fruit>
donneLesFruitsCoutantMoinsQue(prix : Double) : List<Fruit>
donneLeFruit(nom : String) : Fruit?
enregistreLesFruits(fruits : List<Fruit>)
ajouteUnFruit(fruit : Fruit)
}

class FruitDejaPresentException

FruitDejaPresentException <.left. FruitDAO::ajouteUnFruit : << throws >>


class FruitJsonDAO {
    ...
}

class FruitH2DAO {
    ...
}

class FruitCsvDAO {
    ...
}

class FruitSqliteDAO {
    ...
}

class FruitMariaDbDAO {
    ...
}

FruitDAO .left.> Fruit : << uses >>

FruitJsonDAO .up.|> FruitDAO : << realizes >>
FruitH2DAO .up.|> FruitDAO : << realizes >>
FruitSqliteDAO .up.|> FruitDAO : << realizes >>
FruitMariaDbDAO .up.|> FruitDAO : << realizes >>
FruitCsvDAO .up.|> FruitDAO : << realizes >>

FruitSqliteDAO -up[hidden]- FruitH2DAO
FruitMariaDbDAO -up[hidden]- FruitH2DAO

@enduml